version: '3'
services:
  api:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    volumes:
      - database:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=bookclub_dev
      - POSTGRES_DB=bookclub
    expose:
      - "5432:5432"
    ports:
      - "5432:5432"

volumes:
  database: 

